### ISSUE TITLE
release.zip not available in the releases

### ISSUE THREAD

**Issue by praveenvidem** [Rabobank-Archive/azure-functions#1]
Hi,

I've been trying to integrate the azure functions for azure devops compliance as per the script mentioned in [https://github.com/azure-devops-compliance/azure-functions](https://github.com/azure-devops-compliance/azure-functions)

But I could see that following file is not available because of which the function is not getting created in function app.
https://github.com/azure-devops-compliance/azure-functions/releases/latest/download/release.zip

Could you please provide release.zip file so that I can integrate the same ?

**Comment by riezebosch** [comment]
Sorry for the late response, URL seems to be working again.
